== Configuration du plugin

La procédure d'installation :

* S'assurer que le Roomba est correctement paramétré sur le réseau local (procédure via l'application iRobot)
* Eteindre toute application iRobot sur Android ou iOS. Attention : l'utilisation simultanée de l'application iRobot peut provoquer des blocages de communication entre le plugin et le Roomba
* Sur jeedom, installer le plugin, attendre que les dépendances soient installées
* S'assurer que roomba est sur sa base
* Faire une recherche d'équipement depuis la page de configuration. Les roombas sur le réseaux seront automatiquement créés en tant qu'équipement.
* Utiliser le bouton "Récupérer le mot de passe" sur la page de configuration de l'équipement
* Lire les instructions (appuis de 2 sec sur HOME jusqu'à ce que la led WIFI clignotte vert) puis appuyer sur "Continuer"
* Dans les 30 secondes qui suivent, sur le roomba, rester appuyé sur le bouton "Maison" (seulement) pendant 2 secondes (jusqu'à ce qu'il fasse un petit bipbip).